build: false
shallow_clone: true
platform:
  - x86
  - x64
  - Any CPU
cache:
  - c:\tools\php
  - c:\Users\appveyor\AppData\Roaming\Composer\vendor
init:
  - SET PATH=c:\tools\php;%PATH%
  - SET PHP=1
  - SET COMPOSER_NO_INTERACTION=1
  - SET ANSICON=121x90 (121x90)
install:
  - IF EXIST c:\tools\php (SET PHP=0)
  - IF %PHP%==1 cinst -y OpenSSL.Light
  - IF %PHP%==1 cinst -y php
  - cd c:\tools\php
  - IF %PHP%==1 copy php.ini-production php.ini /Y
  - IF %PHP%==1 echo date.timezone="UTC" >> php.ini
  - IF %PHP%==1 echo extension_dir=ext >> php.ini
  - IF %PHP%==1 echo extension=php_openssl.dll >> php.ini
  - IF %PHP%==1 echo extension=php_mbstring.dll >> php.ini
  - IF %PHP%==1 echo extension=php_fileinfo.dll >> php.ini
  - cd %APPVEYOR_BUILD_FOLDER%
  - appveyor DownloadFile https://getcomposer.org/composer.phar
  - php composer.phar global require "fxp/composer-asset-plugin:~1.2.0" --no-interaction  --no-progress
  - php composer.phar config -g github-oauth.github.com %GITHUB_PUBLIC_TOKEN%
  - php composer.phar update --no-interaction --prefer-dist  --no-progress
before_test:
  - git --version
  - php --version
test_script:
  - vendor/bin/phpunit
